/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;

/**
 *
 * @author carlospitre
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.Painter;
import javax.swing.Timer;
import javax.swing.UIDefaults;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
public class grafica extends javax.swing.JFrame {

    /**
     * Creates new form grafica
     */
    Timer  timer;
    public grafica() {
        
        initComponents();
        
        cargarbarra();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtTipo = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtNivel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaxPeso = new javax.swing.JTextField();
        txtMinPeso = new javax.swing.JTextField();
        txtMinNivel = new javax.swing.JTextField();
        txtMaxNivel = new javax.swing.JTextField();
        txtMinTipo = new javax.swing.JTextField();
        txtMaxTipo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaEntradas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        panelNivel = new javax.swing.JPanel();
        panelNivelAgua = new javax.swing.JPanel();
        panelTipo = new javax.swing.JPanel();
        panelPeso = new javax.swing.JPanel();
        panelPeso1 = new javax.swing.JPanel();
        panelNivel1 = new javax.swing.JPanel();
        panelTipo1 = new javax.swing.JPanel();
        panelNivelAgua1 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jLabel7 = new javax.swing.JLabel();
        txtMaximaAgua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNivelAgua = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField4.setText("jTextField1");

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Variables de Entradas"));

        txtTipo.setText("0");
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        txtPeso.setText("0");
        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        txtNivel.setText("0");

        jLabel1.setText("Peso de Ropa");

        jLabel2.setText("Nivel Suciedad");

        jLabel3.setText("Tipo de Tela");

        jLabel4.setText("Universo");

        jLabel5.setText("Min");

        jLabel6.setText("Max");

        txtMaxPeso.setText("0");
        txtMaxPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxPesoActionPerformed(evt);
            }
        });

        txtMinPeso.setText("0");
        txtMinPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinPesoActionPerformed(evt);
            }
        });

        txtMinNivel.setText("0");
        txtMinNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinNivelActionPerformed(evt);
            }
        });

        txtMaxNivel.setText("0");
        txtMaxNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxNivelActionPerformed(evt);
            }
        });

        txtMinTipo.setText("0");
        txtMinTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinTipoActionPerformed(evt);
            }
        });

        txtMaxTipo.setText("0");
        txtMaxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNivel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMinTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMinNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(txtMaxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMinPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addGap(22, 22, 22))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMinNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMinTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grados de Pert. Var. Entradas"));

        textAreaEntradas.setColumns(20);
        textAreaEntradas.setRows(5);
        jScrollPane1.setViewportView(textAreaEntradas);

        jTabbedPane2.addTab("Entradas", jScrollPane1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("hahahahaha\n");
        jScrollPane2.setViewportView(jTextArea2);

        jTabbedPane2.addTab("Salidas", jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelNivel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelNivelLayout = new javax.swing.GroupLayout(panelNivel);
        panelNivel.setLayout(panelNivelLayout);
        panelNivelLayout.setHorizontalGroup(
            panelNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );
        panelNivelLayout.setVerticalGroup(
            panelNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        panelNivelAgua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelNivelAguaLayout = new javax.swing.GroupLayout(panelNivelAgua);
        panelNivelAgua.setLayout(panelNivelAguaLayout);
        panelNivelAguaLayout.setHorizontalGroup(
            panelNivelAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        panelNivelAguaLayout.setVerticalGroup(
            panelNivelAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        panelTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelTipoLayout = new javax.swing.GroupLayout(panelTipo);
        panelTipo.setLayout(panelTipoLayout);
        panelTipoLayout.setHorizontalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        panelTipoLayout.setVerticalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        panelPeso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelPesoLayout = new javax.swing.GroupLayout(panelPeso);
        panelPeso.setLayout(panelPesoLayout);
        panelPesoLayout.setHorizontalGroup(
            panelPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        panelPesoLayout.setVerticalGroup(
            panelPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelPeso1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelPeso1Layout = new javax.swing.GroupLayout(panelPeso1);
        panelPeso1.setLayout(panelPeso1Layout);
        panelPeso1Layout.setHorizontalGroup(
            panelPeso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        panelPeso1Layout.setVerticalGroup(
            panelPeso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelNivel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelNivel1Layout = new javax.swing.GroupLayout(panelNivel1);
        panelNivel1.setLayout(panelNivel1Layout);
        panelNivel1Layout.setHorizontalGroup(
            panelNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );
        panelNivel1Layout.setVerticalGroup(
            panelNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        panelTipo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelTipo1Layout = new javax.swing.GroupLayout(panelTipo1);
        panelTipo1.setLayout(panelTipo1Layout);
        panelTipo1Layout.setHorizontalGroup(
            panelTipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        panelTipo1Layout.setVerticalGroup(
            panelTipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        panelNivelAgua1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelNivelAgua1Layout = new javax.swing.GroupLayout(panelNivelAgua1);
        panelNivelAgua1.setLayout(panelNivelAgua1Layout);
        panelNivelAgua1Layout.setHorizontalGroup(
            panelNivelAgua1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        panelNivelAgua1Layout.setVerticalGroup(
            panelNivelAgua1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(panelPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelNivelAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(panelPeso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTipo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelNivelAgua1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(94, 94, 94))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNivelAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNivelAgua1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNivel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTipo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPeso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(346, 346, 346))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {panelNivel, panelNivelAgua, panelTipo});

        jScrollPane4.setViewportView(jPanel4);

        progressBar.setOrientation(1);
        progressBar.setStringPainted(true);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Variables de Salidas"));

        jLabel7.setText("Nivel Maximo de Agua en Lts");

        txtMaximaAgua.setText("0");
        txtMaximaAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaximaAguaActionPerformed(evt);
            }
        });

        jLabel8.setText("Nivel Del Agua En Lts ");

        txtNivelAgua.setText("0");
        txtNivelAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNivelAguaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNivelAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaximaAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaximaAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNivelAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(239, 239, 239)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1035, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(640, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (parseDouble(txtPeso.getText()) < parseDouble(txtMinPeso.getText())){
            JOptionPane.showMessageDialog(null, "El Peso de La Ropa Debe Ser Mayor Al Valor Minimo Del Conjunto Difuso", "alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (parseDouble(txtNivel.getText()) < parseDouble(txtMinNivel.getText())){
            JOptionPane.showMessageDialog(null, "El Nivel De Suciedad Debe Ser Mayor Al Valor Minimo Del Conjunto Difuso", "alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (parseDouble(txtTipo.getText()) < parseDouble(txtMinTipo.getText())){
            JOptionPane.showMessageDialog(null, "El Tipo de Ropa Debe Ser Mayor Al Valor Minimo Del Conjunto Difuso", "alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        graficaPeso();
        graficaNivel();
        graficaTipo();
        valoresPertenecia();
        desfuzificar();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void desfuzificar(){
        double proporcionAgua,nivelAgua;
        double peso = parseDouble(txtPeso.getText());
        double universoAgua = (parseDouble(txtMaxPeso.getText())*20)/16;
        System.out.println(universoAgua);
        proporcionAgua = (peso * 100)/parseDouble(txtMaxPeso.getText());
        nivelAgua = (universoAgua * proporcionAgua)/100;
        System.out.println(nivelAgua);
        txtNivelAgua.setText(Integer.toString((int) Math.round(nivelAgua)));
        txtMaximaAgua.setText(Integer.toString((int) Math.round(universoAgua)));        
        graficarNivelAgua(nivelAgua,universoAgua);
    }
    
    public void graficarNivelAgua(double nivelAgua, double universo){
        double a = 0;
        double b = universo;
        XYSeries Puntos = new XYSeries("Puntos 1");
        Puntos.add(a, 0);
        Puntos.add((a+b)/2, b);
        Puntos.add(b, 0);
        XYSeries Puntos2 = new XYSeries("Puntos 2");
        Puntos2.add(a, b);
        Puntos2.add((a+b)/2, 0);
        Puntos2.add(b, b);
        XYSeries PuntosRecta = new XYSeries("Recta");
        PuntosRecta.add(nivelAgua,0);
        PuntosRecta.add(nivelAgua, b);
        
        final XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(Puntos);
        dataset.addSeries(Puntos2);
        dataset.addSeries(PuntosRecta);
        JFreeChart chart = ChartFactory.createXYLineChart(
            "Grafica Nivel del Agua", "Universo", "Grado Pertenencia",
            dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel panel = new ChartPanel(chart);        
        panelNivelAgua.setLayout(new java.awt.BorderLayout());
        panelNivelAgua.add(panel);   
        panelNivelAgua.validate();
    }
    
    public  void cargarbarra(){
        UIDefaults defaults = new UIDefaults();
        defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.BLUE));
        defaults.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.BLUE));
        progressBar.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        progressBar.putClientProperty("Nimbus.Overrides", defaults);
      ActionListener updateProBar = new ActionListener() {
              
      public void actionPerformed(ActionEvent ae) {
       
         //nivel minimo y maximo del tanque de la lavadora
          int max, min;
          min=0;
          max=Integer.parseInt(txtMaximaAgua.getText());
         
          progressBar.setMinimum(min);
          progressBar.setMaximum(max);
           
        // obtengo el nivel deseado
        int   nivelDeseado = Integer.parseInt(txtNivelAgua.getText());      
        // obtengo el nivel actual
        int  nivelActual= progressBar.getValue();
             
//niveles para el agua
        if (nivelDeseado > nivelActual){
            
                                if(nivelDeseado == nivelActual){
                                    timer.stop();
                                  }
                                 progressBar.setValue(++nivelActual);                                                           
        }else{
            if (nivelDeseado < nivelActual){
                
                           if(nivelDeseado == nivelActual){
                                timer.stop();
                              }
                           progressBar.setValue(--nivelActual);                                              
            }
        }
 //fin niveles para  agua   
    
      /*int nivel;
      nivel = Integer.parseInt(txtsuciedad.getText()); 
      suciedad(nivel);*/
      
      }

      private void suciedad(int nivelSuciedad) {
                           
       //agregar
                double max, min,pocosucia,sucia,muysucia;
                min=1;
                pocosucia =4;
                sucia =9;
                muysucia =14;
                        
      //niveles para el color
               
                    //niveles normal
                    if (nivelSuciedad >= min && nivelSuciedad < pocosucia) {

                        UIDefaults defaults = new UIDefaults();
                        defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.BLUE));
                        defaults.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.BLUE));
                        progressBar.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
                        progressBar.putClientProperty("Nimbus.Overrides", defaults);

                    } else {
                        //nivel sucio
                        if (nivelSuciedad >= pocosucia && nivelSuciedad < sucia) {
                            UIDefaults defaults = new UIDefaults();
                            defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.LIGHT_GRAY));
                            defaults.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.LIGHT_GRAY));
                            progressBar.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
                            progressBar.putClientProperty("Nimbus.Overrides", defaults);
                        } else {
                            //nivel muy sucio
                            if (nivelSuciedad >= sucia && nivelSuciedad <= muysucia) {
                                UIDefaults defaults = new UIDefaults();
                                defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.GRAY));
                                defaults.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.GRAY));
                                progressBar.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
                                progressBar.putClientProperty("Nimbus.Overrides", defaults);
                            }

                        }
                    }

               
                //fin niveles
            }
     
    };
    timer = new Timer(500, updateProBar);
    timer.start();  
    }
    
    private void valoresPertenecia(){
        double nivel = parseDouble(txtNivel.getText());
        double peso = parseDouble(txtPeso.getText());
        double tipo = parseDouble(txtTipo.getText());
        double porcentajeN,porcentajeP,porcentajeT, complementoN, complementoP, complementoT;
        double aN=parseDouble(txtMinNivel.getText()),aP=parseDouble(txtMinPeso.getText()),aT=parseDouble(txtMinTipo.getText());
        double bN=parseDouble(txtMaxNivel.getText()),bP=parseDouble(txtMaxPeso.getText()),bT=parseDouble(txtMaxTipo.getText());
        double mN = (aN+bN)/2;
        double mP = (aP+bP)/2;
        double mT = (aT+bT)/2;
        String mensajeNivel,mensajePeso,mensajeTipo;
  
        if (nivel >= aN && nivel <= mN){
            porcentajeN = (nivel - aN)/(mN - aN);
            complementoN = 1-porcentajeN;
            mensajeNivel = "El Nivel de Suciedad Pertenece en un " + Math.rint(porcentajeN*100) + "% Al Conjunto Difuso Sucia y en un " + Math.rint(complementoN*100) + "% Al Conjunto Difuso de Poco Sucia";
        }else{
            porcentajeN = (bN - nivel)/(bN - mN);
            complementoN = 1-porcentajeN;
            mensajeNivel = "El Nivel de Suciedad Pertenece en un " + Math.rint(porcentajeN*100) + "% Al Conjunto Difuso Sucia y en un " + Math.rint(complementoN*100) + "% Al Conjunto Difuso Muy Sucia ";
        }
        if (peso >= aP && peso <= mP){
            porcentajeP = (peso - aP)/(mP - aP);
            complementoP = 1-porcentajeP;
            mensajePeso = "El Nivel de Peso Pertenece en un " + Math.rint(porcentajeP*100) + "% Al Conjunto Difuso Pesado y en un " + Math.rint(complementoP*100) + "% Al Conjunto Difuso  Liviano";
        }else{
            porcentajeP = (bP - peso)/(bP - mP);
            complementoP = 1-porcentajeP;
            mensajePeso = "El Nivel de Peso Pertenece en un " + Math.rint(porcentajeP*100) + "% Al Conjunto Difuso Pesado y en un " + Math.rint(complementoP*100) + "% Al Conjunto Difuso Muy Pesado";
        }
        if (tipo >= aT && tipo <= mT){
            porcentajeT = (tipo - aT)/(mT - aT);
            complementoT = 1-porcentajeT;
            mensajeTipo = "El Nivel de Tipo de Ropa Pertenece en un " + Math.rint(porcentajeT*100) + "% Al Conjunto Difuso de Jeans y en un " + Math.rint(complementoT*100) + "% Al Conjunto Difuso de Algodon";
        }else{
            porcentajeT = (bT - tipo)/(bT - mT);
            complementoT = 1-porcentajeT;
            mensajeTipo = "El Nivel de Tipo de Ropa Pertenece en un " + Math.rint(porcentajeT*100) + "% Al Conjunto Difuso de Jeans y en un " + Math.rint(complementoT*100) + "% Al Conjunto Difuso de Seda";
        }
        textAreaEntradas.setText("");
        textAreaEntradas.append(mensajeNivel);
        textAreaEntradas.append(System.getProperty("line.separator"));
        textAreaEntradas.append(mensajePeso);
        textAreaEntradas.append(System.getProperty("line.separator"));
        textAreaEntradas.append(mensajeTipo);
    }
    
    private void graficaNivel(){
        double a = parseDouble(txtMinNivel.getText());
        double b = parseDouble(txtMaxNivel.getText());
        XYSeries Puntos = new XYSeries("Puntos 1");
        Puntos.add(a, 0);
        Puntos.add((a+b)/2, b);
        Puntos.add(b, 0);
        XYSeries Puntos2 = new XYSeries("Puntos 2");
        Puntos2.add(a, b);
        Puntos2.add((a+b)/2, 0);
        Puntos2.add(b, b);
        XYSeries PuntosRecta = new XYSeries("Recta");
        PuntosRecta.add(parseDouble(txtNivel.getText()),0);
        PuntosRecta.add(parseDouble(txtNivel.getText()), b);
        
        final XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(Puntos);
        dataset.addSeries(Puntos2);
        dataset.addSeries(PuntosRecta);
        JFreeChart chart = ChartFactory.createXYLineChart(
            "Grafica Nivel Suciedad", "Universo", "Grado Pertenencia",
            dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel panel = new ChartPanel(chart);        
        panelNivel.setLayout(new java.awt.BorderLayout());
        panelNivel.add(panel);   
        panelNivel.validate();
    }
    
    private void graficaPeso(){
        double a = parseDouble(txtMinPeso.getText());
        double b = parseDouble(txtMaxPeso.getText());
        XYSeries Puntos = new XYSeries("Puntos 1");
        Puntos.add(a, 0);
        Puntos.add((a+b)/2, b);
        Puntos.add(b, 0);
        XYSeries Puntos2 = new XYSeries("Puntos 2");
        Puntos2.add(a, b);
        Puntos2.add((a+b)/2, 0);
        Puntos2.add(b, b);
        XYSeries PuntosRecta = new XYSeries("Recta");
        PuntosRecta.add(parseDouble(txtPeso.getText()),0);
        PuntosRecta.add(parseDouble(txtPeso.getText()), b);
        
        final XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(Puntos);
        dataset.addSeries(Puntos2);
        dataset.addSeries(PuntosRecta);
        JFreeChart chart = ChartFactory.createXYLineChart(
            "Grafica Peso Ropa", "Universo", "Grado Pertenencia",
            dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel panel = new ChartPanel(chart);        
        panelPeso.setLayout(new java.awt.BorderLayout());
        panelPeso.add(panel);   
        panelPeso.validate();
    } 
    
    private void graficaTipo(){
        double a = parseDouble(txtMinTipo.getText());
        double b = parseDouble(txtMaxTipo.getText());
        XYSeries Puntos = new XYSeries("Puntos 1");
        Puntos.add(a, 0);
        Puntos.add((a+b)/2, b);
        Puntos.add(b, 0);
        XYSeries Puntos2 = new XYSeries("Puntos 2");
        Puntos2.add(a, b);
        Puntos2.add((a+b)/2, 0);
        Puntos2.add(b, b);
        XYSeries PuntosRecta = new XYSeries("Recta");
        PuntosRecta.add(parseDouble(txtTipo.getText()),0);
        PuntosRecta.add(parseDouble(txtTipo.getText()), b);
        
        final XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(Puntos);
        dataset.addSeries(Puntos2);
        dataset.addSeries(PuntosRecta);
        JFreeChart chart = ChartFactory.createXYLineChart(
            "Grafica Tipo Ropa", "Universo", "Grado Pertenencia",
            dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel panel = new ChartPanel(chart);        
        panelTipo.setLayout(new java.awt.BorderLayout());
        panelTipo.add(panel);   
        panelTipo.validate();
    }
    
    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void txtMaxPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxPesoActionPerformed

    private void txtMinPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinPesoActionPerformed

    private void txtMinNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinNivelActionPerformed

    private void txtMaxNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxNivelActionPerformed

    private void txtMinTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinTipoActionPerformed

    private void txtMaxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxTipoActionPerformed

    private void txtMaximaAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaximaAguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaximaAguaActionPerformed

    private void txtNivelAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNivelAguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNivelAguaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel panelNivel;
    private javax.swing.JPanel panelNivel1;
    private javax.swing.JPanel panelNivelAgua;
    private javax.swing.JPanel panelNivelAgua1;
    private javax.swing.JPanel panelPeso;
    private javax.swing.JPanel panelPeso1;
    private javax.swing.JPanel panelTipo;
    private javax.swing.JPanel panelTipo1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextArea textAreaEntradas;
    private javax.swing.JTextField txtMaxNivel;
    private javax.swing.JTextField txtMaxPeso;
    private javax.swing.JTextField txtMaxTipo;
    private javax.swing.JTextField txtMaximaAgua;
    private javax.swing.JTextField txtMinNivel;
    private javax.swing.JTextField txtMinPeso;
    private javax.swing.JTextField txtMinTipo;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNivelAgua;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
class MyPainter implements Painter<JProgressBar> {

    private final Color color;

    public MyPainter(Color c1) {
        this.color = c1;
    }
    public void paint(Graphics2D gd, JProgressBar t, int width, int height) {
        gd.setColor(color);
        gd.fillRect(0, 0, width, height);
    }
}
